name: Build the test systemd-nspawn image

on:
  push:
    branches: ["master"]

jobs:
  build-nspawn:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            debootstrap \
            python3 \
            systemd-container
          sudo pip3 install https://github.com/systemd/mkosi/archive/refs/tags/v14.zip
      -
        name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
      -
        name: Build Test Image
        working-directory: ./image
        run: sudo -E mkosi build .
      -
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./image/mkosi.output/debian~*
