[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=tar
CompressOutput=xz
Output=openvpn

[Validation]
Checksum=true

[Build]
# Use bundled build tools instead of host tools
ToolsTree=yes
# Run build and postinst scripts with network access
WithNetwork=true

[Content]
# Enables or disables generation of a bootable image
Bootable=no
# Install the specified distribution packages in the image
Packages=
    apt
    bash
    ca-certificates
    dbus
    easy-rsa
    gettext-base
    iproute2
    less
    nftables
    nano
    openvpn
    procps
    systemd
    zip
    unattended-upgrades
